export const products = [
    {
      id: 1,
      title: "Trendy Logo Print Crew Neck Maroon Fleece Casual Sweatshirt for Fashionable Men",
      color: "Maroon",
      size: "Large",
      price: 39.95,
      oldPrice: 14.99,
      image: "/images/product1.png",
      limitedDeal: true,
      timer: "01:08:09:24",
      quantity: 1,
      progress: 75,
      sellerName: "[Seller/Store Name]",
    },
    {
      id: 2,
      title: "Mens Stylish Colorblock Full Sleeves Regular Wear Sweatshirt for Casual Wear",
      color: "Black",
      size: "XL",
      price: 54.9,
      oldPrice: 18.95,
      image: "/images/product2.png",
      limitedDeal: false,
      quantity: 1,
      sellerName: "[Seller/Store Name]",
    },
    {
      id: 3,
      title: "Stylish Mens Fleece Full Sleeves Fabulous Sweatshirt for Fashionable Men",
      color: "Dark Blue",
      size: "XXL",
      price: 46.95,
      oldPrice: 9.99,
      image: "/images/product3.png",
      limitedDeal: false,
      quantity: 1,
      sellerName: "[Seller/Store Name]",
    },
    {
      id: 4,
      title: "Stylish Mens Fleece Full Sleeves Fabulous Sweatshirt for Fashionable Men",
      color: "Dark Blue",
      size: "XXL",
      price: 46.95,
      oldPrice: 9.99,
      image: "/images/product3.png",
      limitedDeal: false,
      quantity: 1,
      sellerName: "[Seller/Store Name]",
    },

  ];
  