export const products = [
  {
    imageUrl: "/images/card-image1.png",
    title: "Jbl M3 Mini Portable Bluetooth Speaker Amazing Sound Quality...",
    price: "$54.90",
    originalPrice: "$93.95",
    discount: "-40%",
    rating: 3,
    reviews: 4,
  },
  {
    imageUrl: "/images/card-image2.png",
    title: "RONIN R-8500 Sound Junction Wireless Speakers",
    price: "$54.90",
    originalPrice: "$93.95",
    discount: "-40%",
    rating: 3,
    reviews: 0,
  },
  {
    imageUrl: "/images/card-image3.png",
    title: "Morui MS-01 Mini Portable Bluetooth Speakers",
    price: "$54.90",
    originalPrice: "$93.95",
    discount: "-40%",
    rating: 3,
    reviews: 0,
  },
  {
    imageUrl: "/images/card-image4.png",
    title: "SPACE - STORM - 2.1 Multimedia Speakers",
    price: "$54.90",
    originalPrice: "$93.95",
    discount: "-40%",
    rating: 3,
    reviews: 3,
  },
  {
    imageUrl: "/images/card-image5.png",
    title: "USB Microphone for Gaming, Streaming, Recording, Podcasting...",
    price: "$54.90",
    originalPrice: "$93.95",
    discount: "-40%",
    rating: 3,
    reviews: 2,
  },
  {
    imageUrl: "/images/card-image1.png",
    title: "Morui MS-02 Compact Bluetooth Speaker",
    price: "$59.99",
    originalPrice: "$99.99",
    discount: "-40%",
    rating: 4,
    reviews: 6,
  },
  {
    imageUrl: "/images/card-image2.png",
    title: "Wireless Earbuds with Crystal Clear Sound",
    price: "$49.90",
    originalPrice: "$89.95",
    discount: "-45%",
    rating: 5,
    reviews: 10,
  },
  {
    imageUrl: "/images/card-image3.png",
    title: "Portable Smart Speaker with Alexa Integration",
    price: "$69.99",
    originalPrice: "$129.99",
    discount: "-40%",
    rating: 4,
    reviews: 8,
  },
  {
    imageUrl: "/images/card-image4.png",
    title: "High-Quality Wired Gaming Headset",
    price: "$39.90",
    originalPrice: "$69.95",
    discount: "-43%",
    rating: 4,
    reviews: 12,
  },
  {
    imageUrl: "/images/card-image5.png",
    title: "Noise Cancelling Over-Ear Bluetooth Headphones",
    price: "$79.90",
    originalPrice: "$139.95",
    discount: "-42%",
    rating: 5,
    reviews: 15,
  },
  {
    imageUrl: "/images/card-image1.png",
    title: "Wireless Charging Pad for All Devices",
    price: "$29.90",
    originalPrice: "$49.95",
    discount: "-40%",
    rating: 4,
    reviews: 7,
  },
  {
    imageUrl: "/images/card-image2.png",
    title: "Compact USB-C Fast Charger (20W)",
    price: "$19.90",
    originalPrice: "$34.95",
    discount: "-43%",
    rating: 5,
    reviews: 22,
  },
  {
    imageUrl: "/images/card-image3.png",
    title: "Home Theater Sound System with Subwoofer",
    price: "$249.99",
    originalPrice: "$399.99",
    discount: "-38%",
    rating: 5,
    reviews: 18,
  },
  {
    imageUrl: "/images/card-image4.png",
    title: "Ultra-Portable Mini Projector",
    price: "$99.90",
    originalPrice: "$169.95",
    discount: "-41%",
    rating: 4,
    reviews: 11,
  },
  {
    imageUrl: "/images/card-image5.png",
    title: "Bluetooth Keyboard with Touchpad",
    price: "$45.90",
    originalPrice: "$69.95",
    discount: "-34%",
    rating: 4,
    reviews: 8,
  },
  {
    imageUrl: "/images/card-image1.png",
    title: "Smart LED Light Bulbs (Pack of 4)",
    price: "$39.90",
    originalPrice: "$69.95",
    discount: "-43%",
    rating: 4,
    reviews: 13,
  },
  {
    imageUrl: "/images/card-image2.png",
    title: "Action Camera with 4K Video Recording",
    price: "$129.90",
    originalPrice: "$199.95",
    discount: "-35%",
    rating: 5,
    reviews: 20,
  },
  {
    imageUrl: "/images/card-image3.png",
    title: "Wireless Gaming Mouse with RGB Lighting",
    price: "$39.90",
    originalPrice: "$69.95",
    discount: "-43%",
    rating: 4,
    reviews: 14,
  },
  {
    imageUrl: "/images/card-image4.png",
    title: "Portable Power Bank 10,000mAh",
    price: "$29.90",
    originalPrice: "$49.95",
    discount: "-40%",
    rating: 5,
    reviews: 19,
  },
  {
    imageUrl: "/images/card-image5.png",
    title: "Compact DSLR Camera for Beginners",
    price: "$299.90",
    originalPrice: "$499.95",
    discount: "-40%",
    rating: 5,
    reviews: 25,
  },
];
